### ISSUE TITLE
question out of interest

### ISSUE THREAD

**Issue by waudinio27** [tblume1992/ThymeBoost#26]
Hello Tyler! 

I hope you are fine. I was reading that the future of ARIMA is the SARIMAX model. As it is more dynamic. Is the reason why it is not used in your program, because it does not estimate the components by itself like auto.arima? 

Thanks and greetings.

**Comment by tblume1992** [comment]
SARIMAX is just the generalization to allow for seasonality (S) and exogenous factors (X). So if your series has no seasonality or exogenous then you will use an arima. The reason why SARIMAX is NOT used in ThymeBoost is because it breaks how ThymeBoost learns each component of the time series. 

More specifically, SARIMAX learns about each component (trend, seasonality, exogenous) simultaneously whereas ThymeBoost approximates one piece (like trend) then passes that to the next component to learn. We can do this with just an arima if we interpret that as the 'trend' but any model that 'learns' multiple components at once won't work in the framework. 

Hopefully that makes sense!
